### PR TITLE
fix: preserve leading zeros in testdata filenames during natural sort

### LINKED ISSUE #35: Fail on running when testdata filenames include a number with prefix 0
For example, `a01` will be converted into `a1`, but there isn't a `a1.in`.

### PR DESCRIPTION
**Pull request by armorbreak001**
## Problem

When testdata filenames contain leading zeros (e.g. `a01.in`, `a02.in`), running Atiro fails because the filename gets mangled to `a1.in` which does not exist.

**Root cause:** In `lib/judger.js`, `splitByDigitsAndNonDigits()` converts digit segments via `Number()`, which strips leading zeros. After sorting, `data.join('')\) extracts `__n` from wrapper objects for comparison
- Final join step unwraps objects back to their raw string form

This preserves natural sort ordering (a1 < a2 < a10) while keeping leading zero padding intact in the resulting filename.

### CODE REVIEW

**Review by Sukwants — APPROVED** [review]

File: lib/judger.js [hunk 1]
```diff
@@ -23,15 +23,19 @@ function generateRandomString(length) {
 
 function splitByDigitsAndNonDigits(input) {
   const segments = input.split(/(\d+)/).filter(Boolean);
-  return segments.map(segment => /^\d+$/.test(segment) ? Number(segment) : segment);
+  return segments.map(segment => /^\d+$/.test(segment)
+    ? { __n: parseInt(segment, 10), __s: segment }
```
Comment (2745518585) [inline lib/judger.js:27]: 优秀码风

**Review by 2745518585 — APPROVED** [review]
凡是 Sukwants 作出的决策，我们都坚决维护
